package emea_ssa.docsample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InformationList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<emea_ssa.docsample.Information> infoList;

   public InformationList()
   {
   }

   public java.util.List<emea_ssa.docsample.Information> getInfoList()
   {
      return this.infoList;
   }

   public void setInfoList(
         java.util.List<emea_ssa.docsample.Information> infoList)
   {
      this.infoList = infoList;
   }

   public InformationList(
         java.util.List<emea_ssa.docsample.Information> infoList)
   {
      this.infoList = infoList;
   }

}