package emea_ssa.docsample;

import org.jbpm.document.Document;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Information implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String title;
   private Document doc;

   private java.lang.String tags;

   private java.math.BigDecimal version;

   public Information()
   {
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public Information(java.lang.String title)
   {
      this.title = title;
   }

   public Document getDoc()
   {
      return doc;
   }

   public void setDoc(Document doc)
   {
      this.doc = doc;
   }

   public java.lang.String getTags()
   {
      return this.tags;
   }

   public void setTags(java.lang.String tags)
   {
      this.tags = tags;
   }

   public java.math.BigDecimal getVersion()
   {
      return this.version;
   }

   public void setVersion(java.math.BigDecimal version)
   {
      this.version = version;
   }

   public Information(java.lang.String title, org.jbpm.document.Document doc,
         java.lang.String tags, java.math.BigDecimal version)
   {
      this.title = title;
      this.doc = doc;
      this.tags = tags;
      this.version = version;
   }

}